package com.travel.withaeng.common.cd

enum class CountryCd (

    val continentCd: String,
    val countryCd : String,
    val countryNm : String

) {

    KOREA(ContinentCd.EAST_ASIA.continentCd,"KOREA", "한국"),
    JAPAN(ContinentCd.EAST_ASIA.continentCd,"JAPAN", "일본"),
    HONG_KONG(ContinentCd.EAST_ASIA.continentCd,"HONG_KONG", "홍콩"),
    MACAO(ContinentCd.EAST_ASIA.continentCd,"MACAO", "마카오"),
    TAIWAN(ContinentCd.EAST_ASIA.continentCd,"TAIWAN", "대만"),
    CHINA(ContinentCd.EAST_ASIA.continentCd,"CHINA", "중국"),
    MONGOLIA(ContinentCd.EAST_ASIA.continentCd,"MONGOLIA", "몽골"),

    SINGAPORE(ContinentCd.SOUTHEAST_ASIA.continentCd,"SINGAPORE","싱가포르"),
    EAST_TIMOR(ContinentCd.SOUTHEAST_ASIA.continentCd,"EAST_TIMOR","동티모르"),
    MYANMAR(ContinentCd.SOUTHEAST_ASIA.continentCd,"MYANMAR","미얀마"),
    CAMBODIA(ContinentCd.SOUTHEAST_ASIA.continentCd,"CAMBODIA","캄보디아"),
    LAOS(ContinentCd.SOUTHEAST_ASIA.continentCd,"LAOS","라오스"),
    PHILIPPINES(ContinentCd.SOUTHEAST_ASIA.continentCd,"PHILIPPINES","필리핀"),
    MALAYSIA(ContinentCd.SOUTHEAST_ASIA.continentCd,"MALAYSIA","말레이시아"),
    INDONESIA(ContinentCd.SOUTHEAST_ASIA.continentCd,"INDONESIA","인도네시아"),
    THAILAND(ContinentCd.SOUTHEAST_ASIA.continentCd,"THAILAND","태국"),
    VIETNAM(ContinentCd.SOUTHEAST_ASIA.continentCd,"VIETNAM","베트남"),
    BRUNEI(ContinentCd.SOUTHEAST_ASIA.continentCd,"BRUNEI","브루나이"),

    UZBEKISTAN(ContinentCd.CENTRAL_ASIA.continentCd,"UZBEKISTAN","우즈베키스탄"),
    BANGLADESH(ContinentCd.CENTRAL_ASIA.continentCd,"BANGLADESH","방글라데시"),
    AZERBAIJAN(ContinentCd.CENTRAL_ASIA.continentCd,"AZERBAIJAN","아제르바이잔"),
    BUTANE(ContinentCd.CENTRAL_ASIA.continentCd,"BUTANE","부탄"),
    AFGHANISTAN(ContinentCd.CENTRAL_ASIA.continentCd,"AFGHANISTAN","아프가니스탄"),
    TAJIKISTAN(ContinentCd.CENTRAL_ASIA.continentCd,"TAJIKISTAN","타지키스탄"),
    KYRGYZSTAN(ContinentCd.CENTRAL_ASIA.continentCd,"KYRGYZSTAN","키르기스스탄"),
    KAZAKHSTAN(ContinentCd.CENTRAL_ASIA.continentCd,"KAZAKHSTAN","카자흐스탄"),
    TURKMENISTAN(ContinentCd.CENTRAL_ASIA.continentCd,"TURKMENISTAN","투르크메니스탄"),
    TIBET(ContinentCd.CENTRAL_ASIA.continentCd,"TIBET","티베트"),

    ARAB_EMIRATES(ContinentCd.WESTERN_ASIA.continentCd,"ARAB_EMIRATES","아랍에미리트"),
    JORDAN(ContinentCd.WESTERN_ASIA.continentCd,"JORDAN","요르단"),
    YEMEN(ContinentCd.WESTERN_ASIA.continentCd,"YEMEN","예멘"),
    SYRIA(ContinentCd.WESTERN_ASIA.continentCd,"SYRIA","시리아"),
    IRAN(ContinentCd.WESTERN_ASIA.continentCd,"IRAN","이란"),
    PAKISTAN(ContinentCd.WESTERN_ASIA.continentCd,"PAKISTAN","파키스탄"),
    CYPRUS(ContinentCd.WESTERN_ASIA.continentCd,"CYPRUS","키프로스"),
    SRI_LANKA(ContinentCd.WESTERN_ASIA.continentCd,"SRI_LANKA","스리랑카"),
    MALDIVE(ContinentCd.WESTERN_ASIA.continentCd,"MALDIVE","몰디브"),
    BAHRAIN(ContinentCd.WESTERN_ASIA.continentCd,"BAHRAIN","바레인"),
    LRAQ(ContinentCd.WESTERN_ASIA.continentCd,"LRAQ","이라크"),
    PALESTINE(ContinentCd.WESTERN_ASIA.continentCd,"PALESTINE","팔레스타인"),
    OMAN(ContinentCd.WESTERN_ASIA.continentCd,"OMAN","오만"),
    INDIA(ContinentCd.WESTERN_ASIA.continentCd,"INDIA","인도"),
    NEPAL(ContinentCd.WESTERN_ASIA.continentCd,"NEPAL","네팔"),
    ISRAEL(ContinentCd.WESTERN_ASIA.continentCd,"ISRAEL","이스라엘"),
    CATARRH(ContinentCd.WESTERN_ASIA.continentCd,"CATARRH","카타르"),
    LEBANON(ContinentCd.WESTERN_ASIA.continentCd,"LEBANON","레바논"),
    SAUDI_ARABIA(ContinentCd.WESTERN_ASIA.continentCd,"SAUDI_ARABIA","사우디아라비아"),
    KUWAIT(ContinentCd.WESTERN_ASIA.continentCd,"KUWAIT","쿠웨이트"),
    ARMENIA(ContinentCd.WESTERN_ASIA.continentCd,"ARMENIA","아르메니아"),

    GEORGIA(ContinentCd.EUROPE.continentCd,"GEORGIA","조지아"),
    MALTA(ContinentCd.EUROPE.continentCd,"MALTA","몰타"),
    MOLDOVA(ContinentCd.EUROPE.continentCd,"MOLDOVA","몰도바"),
    MONTENEGRO(ContinentCd.EUROPE.continentCd,"MONTENEGRO","몬테네그로"),
    MONACO(ContinentCd.EUROPE.continentCd,"MONACO","모나코"),
    MACEDONIA(ContinentCd.EUROPE.continentCd,"MACEDONIA","마케도니아"),
    LIECHTENSTEIN(ContinentCd.EUROPE.continentCd,"LIECHTENSTEIN","리히텐슈타인"),
    LITHUANIA(ContinentCd.EUROPE.continentCd,"LITHUANIA","리투아니아"),
    LUXEMBOURG(ContinentCd.EUROPE.continentCd,"LUXEMBOURG","룩셈부르크"),
    ROMANIA(ContinentCd.EUROPE.continentCd,"ROMANIA","루마니아"),
    VATICAN(ContinentCd.EUROPE.continentCd,"VATICAN","바티칸"),
    BELARUS(ContinentCd.EUROPE.continentCd,"BELARUS","벨라루스"),
    BOSNIA_HERCEGOVINA(ContinentCd.EUROPE.continentCd,"BOSNIA_HERCEGOVINA","보스니아헤르체코비나"),
    CROATIA(ContinentCd.EUROPE.continentCd,"CROATIA","크로아티아"),
    UKRAINE(ContinentCd.EUROPE.continentCd,"UKRAINE","우크라이나"),
    ESTONIA(ContinentCd.EUROPE.continentCd,"ESTONIA","에스토니아"),
    ALBANIA(ContinentCd.EUROPE.continentCd,"ALBANIA","알바니아"),
    ANDORRA(ContinentCd.EUROPE.continentCd,"ANDORRA","안도라"),
    SLOVAKIA(ContinentCd.EUROPE.continentCd,"SLOVAKIA","슬로바키아"),
    SERBIA(ContinentCd.EUROPE.continentCd,"SERBIA","세르비아"),
    SAN_MARINO(ContinentCd.EUROPE.continentCd,"SAN_MARINO","산마리노"),
    BULGARIA(ContinentCd.EUROPE.continentCd,"BULGARIA","불가리아"),
    LATVIA(ContinentCd.EUROPE.continentCd,"LATVIA","라트비아"),
    SLOVENIA(ContinentCd.EUROPE.continentCd,"SLOVENIA","슬로베니아"),
    PORTUGAL(ContinentCd.EUROPE.continentCd,"PORTUGAL","포르투갈"),
    SWISS(ContinentCd.EUROPE.continentCd,"SWISS","스위스"),
    GERMANY(ContinentCd.EUROPE.continentCd,"GERMANY","독일"),
    NETHERLAND(ContinentCd.EUROPE.continentCd,"NETHERLAND","네덜란드"),
    AUSTRIA(ContinentCd.EUROPE.continentCd,"AUSTRIA","오스트리아"),
    ENGLAND(ContinentCd.EUROPE.continentCd,"ENGLAND","영국"),
    SPAIN(ContinentCd.EUROPE.continentCd,"SPAIN","스페인"),
    TURKIYE(ContinentCd.EUROPE.continentCd,"TURKIYE","터키"),
    ITALY(ContinentCd.EUROPE.continentCd,"ITALY","이탈리아"),
    POLAND(ContinentCd.EUROPE.continentCd,"POLAND","폴란드"),
    ICELAND(ContinentCd.EUROPE.continentCd,"ICELAND","아이슬란드"),
    FINLAND(ContinentCd.EUROPE.continentCd,"FINLAND","핀란드"),
    CZECHIA(ContinentCd.EUROPE.continentCd,"CZECHIA","체코"),
    BELGIUM(ContinentCd.EUROPE.continentCd,"BELGIUM","벨기에"),
    HUNGARY(ContinentCd.EUROPE.continentCd,"HUNGARY","헝가리"),
    IRELAND(ContinentCd.EUROPE.continentCd,"IRELAND","아일랜드"),
    RUSSIA(ContinentCd.EUROPE.continentCd,"RUSSIA","러시아"),
    GREECE(ContinentCd.EUROPE.continentCd,"GREECE","그리스"),
    DENMARK(ContinentCd.EUROPE.continentCd,"DENMARK","덴마크"),
    NORWAY(ContinentCd.EUROPE.continentCd,"NORWAY","노르웨이"),
    SWEDEN(ContinentCd.EUROPE.continentCd,"SWEDEN","스웨덴"),
    FRANCE(ContinentCd.EUROPE.continentCd,"FRANCE","프랑스"),

}