package com.travel.withaeng.common.cd

enum class CountryCd (

    val continentCd: String,
    val countryCd : String,
    val countryNm : String

) {

    KOREA(ContinentCd.EAST_ASIA.continentCd,"KOREA", "한국"),
    JAPAN(ContinentCd.EAST_ASIA.continentCd,"JAPAN", "일본"),
    HONG_KONG(ContinentCd.EAST_ASIA.continentCd,"HONG_KONG", "홍콩"),
    MACAO(ContinentCd.EAST_ASIA.continentCd,"MACAO", "마카오"),
    TAIWAN(ContinentCd.EAST_ASIA.continentCd,"TAIWAN", "대만"),
    CHINA(ContinentCd.EAST_ASIA.continentCd,"CHINA", "중국"),
    MONGOLIA(ContinentCd.EAST_ASIA.continentCd,"MONGOLIA", "몽골"),

    SINGAPORE(ContinentCd.SOUTHEAST_ASIA.continentCd,"SINGAPORE","싱가포르"),
    EAST_TIMOR(ContinentCd.SOUTHEAST_ASIA.continentCd,"EAST_TIMOR","동티모르"),
    MYANMAR(ContinentCd.SOUTHEAST_ASIA.continentCd,"MYANMAR","미얀마"),
    CAMBODIA(ContinentCd.SOUTHEAST_ASIA.continentCd,"CAMBODIA","캄보디아"),
    LAOS(ContinentCd.SOUTHEAST_ASIA.continentCd,"LAOS","라오스"),
    PHILIPPINES(ContinentCd.SOUTHEAST_ASIA.continentCd,"PHILIPPINES","필리핀"),
    MALAYSIA(ContinentCd.SOUTHEAST_ASIA.continentCd,"MALAYSIA","말레이시아"),
    INDONESIA(ContinentCd.SOUTHEAST_ASIA.continentCd,"INDONESIA","인도네시아"),
    THAILAND(ContinentCd.SOUTHEAST_ASIA.continentCd,"THAILAND","태국"),
    VIETNAM(ContinentCd.SOUTHEAST_ASIA.continentCd,"VIETNAM","베트남"),
    BRUNEI(ContinentCd.SOUTHEAST_ASIA.continentCd,"BRUNEI","브루나이"),

    UZBEKISTAN(ContinentCd.CENTRAL_ASIA.continentCd,"UZBEKISTAN","우즈베키스탄"),
    BANGLADESH(ContinentCd.CENTRAL_ASIA.continentCd,"BANGLADESH","방글라데시"),
    AZERBAIJAN(ContinentCd.CENTRAL_ASIA.continentCd,"AZERBAIJAN","아제르바이잔"),
    BUTANE(ContinentCd.CENTRAL_ASIA.continentCd,"BUTANE","부탄"),
    AFGHANISTAN(ContinentCd.CENTRAL_ASIA.continentCd,"AFGHANISTAN","아프가니스탄"),
    TAJIKISTAN(ContinentCd.CENTRAL_ASIA.continentCd,"TAJIKISTAN","타지키스탄"),
    KYRGYZSTAN(ContinentCd.CENTRAL_ASIA.continentCd,"KYRGYZSTAN","키르기스스탄"),
    KAZAKHSTAN(ContinentCd.CENTRAL_ASIA.continentCd,"KAZAKHSTAN","카자흐스탄"),
    TURKMENISTAN(ContinentCd.CENTRAL_ASIA.continentCd,"TURKMENISTAN","투르크메니스탄"),
    TIBET(ContinentCd.CENTRAL_ASIA.continentCd,"TIBET","티베트"),

    ARAB_EMIRATES(ContinentCd.WESTERN_ASIA.continentCd,"ARAB_EMIRATES","아랍에미리트"),
    JORDAN(ContinentCd.WESTERN_ASIA.continentCd,"JORDAN","요르단"),
    YEMEN(ContinentCd.WESTERN_ASIA.continentCd,"YEMEN","예멘"),
    SYRIA(ContinentCd.WESTERN_ASIA.continentCd,"SYRIA","시리아"),
    IRAN(ContinentCd.WESTERN_ASIA.continentCd,"IRAN","이란"),
    PAKISTAN(ContinentCd.WESTERN_ASIA.continentCd,"PAKISTAN","파키스탄"),
    CYPRUS(ContinentCd.WESTERN_ASIA.continentCd,"CYPRUS","키프로스"),
    SRI_LANKA(ContinentCd.WESTERN_ASIA.continentCd,"SRI_LANKA","스리랑카"),
    MALDIVE(ContinentCd.WESTERN_ASIA.continentCd,"MALDIVE","몰디브"),
    BAHRAIN(ContinentCd.WESTERN_ASIA.continentCd,"BAHRAIN","바레인"),
    LRAQ(ContinentCd.WESTERN_ASIA.continentCd,"LRAQ","이라크"),
    PALESTINE(ContinentCd.WESTERN_ASIA.continentCd,"PALESTINE","팔레스타인"),
    OMAN(ContinentCd.WESTERN_ASIA.continentCd,"OMAN","오만"),
    INDIA(ContinentCd.WESTERN_ASIA.continentCd,"INDIA","인도"),
    NEPAL(ContinentCd.WESTERN_ASIA.continentCd,"NEPAL","네팔"),
    ISRAEL(ContinentCd.WESTERN_ASIA.continentCd,"ISRAEL","이스라엘"),
    CATARRH(ContinentCd.WESTERN_ASIA.continentCd,"CATARRH","카타르"),
    LEBANON(ContinentCd.WESTERN_ASIA.continentCd,"LEBANON","레바논"),
    SAUDI_ARABIA(ContinentCd.WESTERN_ASIA.continentCd,"SAUDI_ARABIA","사우디아라비아"),
    KUWAIT(ContinentCd.WESTERN_ASIA.continentCd,"KUWAIT","쿠웨이트"),
    ARMENIA(ContinentCd.WESTERN_ASIA.continentCd,"ARMENIA","아르메니아"),

    GEORGIA(ContinentCd.EUROPE.continentCd,"GEORGIA","조지아"),
    MALTA(ContinentCd.EUROPE.continentCd,"MALTA","몰타"),
    MOLDOVA(ContinentCd.EUROPE.continentCd,"MOLDOVA","몰도바"),
    MONTENEGRO(ContinentCd.EUROPE.continentCd,"MONTENEGRO","몬테네그로"),
    MONACO(ContinentCd.EUROPE.continentCd,"MONACO","모나코"),
    MACEDONIA(ContinentCd.EUROPE.continentCd,"MACEDONIA","마케도니아"),
    LIECHTENSTEIN(ContinentCd.EUROPE.continentCd,"LIECHTENSTEIN","리히텐슈타인"),
    LITHUANIA(ContinentCd.EUROPE.continentCd,"LITHUANIA","리투아니아"),
    LUXEMBOURG(ContinentCd.EUROPE.continentCd,"LUXEMBOURG","룩셈부르크"),
    ROMANIA(ContinentCd.EUROPE.continentCd,"ROMANIA","루마니아"),
    VATICAN(ContinentCd.EUROPE.continentCd,"VATICAN","바티칸"),
    BELARUS(ContinentCd.EUROPE.continentCd,"BELARUS","벨라루스"),
    BOSNIA_HERCEGOVINA(ContinentCd.EUROPE.continentCd,"BOSNIA_HERCEGOVINA","보스니아헤르체코비나"),
    CROATIA(ContinentCd.EUROPE.continentCd,"CROATIA","크로아티아"),
    UKRAINE(ContinentCd.EUROPE.continentCd,"UKRAINE","우크라이나"),
    ESTONIA(ContinentCd.EUROPE.continentCd,"ESTONIA","에스토니아"),
    ALBANIA(ContinentCd.EUROPE.continentCd,"ALBANIA","알바니아"),
    ANDORRA(ContinentCd.EUROPE.continentCd,"ANDORRA","안도라"),
    SLOVAKIA(ContinentCd.EUROPE.continentCd,"SLOVAKIA","슬로바키아"),
    SERBIA(ContinentCd.EUROPE.continentCd,"SERBIA","세르비아"),
    SAN_MARINO(ContinentCd.EUROPE.continentCd,"SAN_MARINO","산마리노"),
    BULGARIA(ContinentCd.EUROPE.continentCd,"BULGARIA","불가리아"),
    LATVIA(ContinentCd.EUROPE.continentCd,"LATVIA","라트비아"),
    SLOVENIA(ContinentCd.EUROPE.continentCd,"SLOVENIA","슬로베니아"),
    PORTUGAL(ContinentCd.EUROPE.continentCd,"PORTUGAL","포르투갈"),
    SWISS(ContinentCd.EUROPE.continentCd,"SWISS","스위스"),
    GERMANY(ContinentCd.EUROPE.continentCd,"GERMANY","독일"),
    NETHERLAND(ContinentCd.EUROPE.continentCd,"NETHERLAND","네덜란드"),
    AUSTRIA(ContinentCd.EUROPE.continentCd,"AUSTRIA","오스트리아"),
    ENGLAND(ContinentCd.EUROPE.continentCd,"ENGLAND","영국"),
    SPAIN(ContinentCd.EUROPE.continentCd,"SPAIN","스페인"),
    TURKIYE(ContinentCd.EUROPE.continentCd,"TURKIYE","터키"),
    ITALY(ContinentCd.EUROPE.continentCd,"ITALY","이탈리아"),
    POLAND(ContinentCd.EUROPE.continentCd,"POLAND","폴란드"),
    ICELAND(ContinentCd.EUROPE.continentCd,"ICELAND","아이슬란드"),
    FINLAND(ContinentCd.EUROPE.continentCd,"FINLAND","핀란드"),
    CZECHIA(ContinentCd.EUROPE.continentCd,"CZECHIA","체코"),
    BELGIUM(ContinentCd.EUROPE.continentCd,"BELGIUM","벨기에"),
    HUNGARY(ContinentCd.EUROPE.continentCd,"HUNGARY","헝가리"),
    IRELAND(ContinentCd.EUROPE.continentCd,"IRELAND","아일랜드"),
    RUSSIA(ContinentCd.EUROPE.continentCd,"RUSSIA","러시아"),
    GREECE(ContinentCd.EUROPE.continentCd,"GREECE","그리스"),
    DENMARK(ContinentCd.EUROPE.continentCd,"DENMARK","덴마크"),
    NORWAY(ContinentCd.EUROPE.continentCd,"NORWAY","노르웨이"),
    SWEDEN(ContinentCd.EUROPE.continentCd,"SWEDEN","스웨덴"),
    FRANCE(ContinentCd.EUROPE.continentCd,"FRANCE","프랑스"),

    AUSTRALIA(ContinentCd.OCEANIA.continentCd,"AUSTRALIA","호주"),
    PALAU(ContinentCd.OCEANIA.continentCd,"PALAU","팔라우"),
    PAPUA_NEW_GUINEA(ContinentCd.OCEANIA.continentCd,"PAPUA_NEW_GUINEA","파푸아뉴기니"),
    TONGA(ContinentCd.OCEANIA.continentCd, "TONGA", "퉁가"),
    KIRIBATI(ContinentCd.OCEANIA.continentCd, "KIRIBATI", "키리바시"),
    SOLOMON_ISLAND(ContinentCd.OCEANIA.continentCd, "SOLOMON_ISLAND", "솔로몬제도"),
    SAMOA(ContinentCd.OCEANIA.continentCd, "SAMOA", "사모아"),

    TUNISIA(ContinentCd.AFRICA.continentCd, "TUNISIA", "튀니지"),
    ANGOLA(ContinentCd.AFRICA.continentCd, "ANGOLA", "앙골라"),
    ALGERIA(ContinentCd.AFRICA.continentCd, "ALGERIA", "알제리"),
    SIERRA_LEONE(ContinentCd.AFRICA.continentCd, "SIERRA_LEONE", "시에라리온"),
    SUDAN(ContinentCd.AFRICA.continentCd, "SUDAN", "수단"),
    SOMALIA(ContinentCd.AFRICA.continentCd, "SOMALIA", "소말리아"),
    SEYCHELLES(ContinentCd.AFRICA.continentCd, "SEYCHELLES", "세이셸"),
    SENEGAL(ContinentCd.AFRICA.continentCd, "SENEGAL", "세네갈"),
    UGANDA(ContinentCd.AFRICA.continentCd, "UGANDA", "우간다"),
    ZAMBIA(ContinentCd.AFRICA.continentCd, "ZAMBIA", "잠비아"),
    EQUATORIAL_GUINEA(ContinentCd.AFRICA.continentCd, "EQUATORIAL_GUINEA", "적도기니"),
    TOGO(ContinentCd.AFRICA.continentCd, "TOGO", "토고"),
    CONGO(ContinentCd.AFRICA.continentCd, "CONGO", "콩고"),
    COTE_D_IVOIRE(ContinentCd.AFRICA.continentCd, "COTE_D_IVOIRE", "코트디부아르"),
    COMOROS(ContinentCd.AFRICA.continentCd, "COMOROS", "코모로"),
    ZIMBABWE(ContinentCd.AFRICA.continentCd, "ZIMBABWE", "짐바브웨"),
    DJIBOUTI(ContinentCd.AFRICA.continentCd, "DJIBOUTI", "지부티"),
    CENTRAL_AFRICAN_REPUBLIC(ContinentCd.AFRICA.continentCd, "CENTRAL_AFRICAN_REPUBLIC", "중앙아프리카공화국"),
    BURUNDI(ContinentCd.AFRICA.continentCd, "BURUNDI", "부룬디"),
    BURKINA_FASO(ContinentCd.AFRICA.continentCd, "BURKINA_FASO", "부르키나파소"),
    GUINEA_BISSAU(ContinentCd.AFRICA.continentCd, "GUINEA_BISSAU", "기니비사우"),
    BOTSWANA(ContinentCd.AFRICA.continentCd, "BOTSWANA", "보츠와나"),
    GUINEA(ContinentCd.AFRICA.continentCd, "GUINEA", "기니"),
    GAMBIA(ContinentCd.AFRICA.continentCd, "GAMBIA", "감비아"),
    GABON(ContinentCd.AFRICA.continentCd, "GABON", "가봉"),
    GHANA(ContinentCd.AFRICA.continentCd, "GHANA", "가나"),
    MOROCCO(ContinentCd.AFRICA.continentCd, "MOROCCO", "모로코"),
    NAMIBIA(ContinentCd.AFRICA.continentCd, "NAMIBIA", "나미비아"),
    KENYA(ContinentCd.AFRICA.continentCd, "KENYA", "케냐"),
    ETHIOPIA(ContinentCd.AFRICA.continentCd, "ETHIOPIA", "에티오피아"),
    TANZANIA(ContinentCd.AFRICA.continentCd, "TANZANIA", "탄자니아"),
    NIGERIA(ContinentCd.AFRICA.continentCd, "NIGERIA", "나이지리아"),
    BENIN(ContinentCd.AFRICA.continentCd, "BENIN", "베넹"),
    NIGER(ContinentCd.AFRICA.continentCd, "NIGER", "니제르"),
    MOZAMBIQUE(ContinentCd.AFRICA.continentCd, "MOZAMBIQUE", "모잠비크"),
    MAURITANIA(ContinentCd.AFRICA.continentCd, "MAURITANIA", "모리타니"),
    MAURITIUS(ContinentCd.AFRICA.continentCd, "MAURITIUS", "모리셔스"),
    MALI(ContinentCd.AFRICA.continentCd, "MALI", "말리"),
    MALAWI(ContinentCd.AFRICA.continentCd, "MALAWI", "말라위"),
    MADAGASCAR(ContinentCd.AFRICA.continentCd, "MADAGASCAR", "마다가스카르"),
    LIBYA(ContinentCd.AFRICA.continentCd, "LIBYA", "리비아"),
    RWANDA(ContinentCd.AFRICA.continentCd, "RWANDA", "르완다"),
    LESOTHO(ContinentCd.AFRICA.continentCd, "LESOTHO", "레소토"),
    LIBERIA(ContinentCd.AFRICA.continentCd, "LIBERIA", "라이베리아"),
    EGYPT(ContinentCd.AFRICA.continentCd, "EGYPT", "이집트"),

    UNITED_STATES(ContinentCd.NORTH_AMERICA.continentCd, "UNITED_STATES", "미국"),
    CANADA(ContinentCd.NORTH_AMERICA.continentCd,"CANADA", "캐나다"),
    MEXICO(ContinentCd.NORTH_AMERICA.continentCd,"MEXICO","멕시코"),
    ANTIGUA_AND_BARBUDA(ContinentCd.NORTH_AMERICA.continentCd, "ANTIGUA_AND_BARBUDA", "앤티가바부다"),
    ARUBA(ContinentCd.NORTH_AMERICA.continentCd, "ARUBA", "아루바"),
    ANGUILLA(ContinentCd.NORTH_AMERICA.continentCd, "ANGUILLA", "앵귈라"),
    ANTARCTICA(ContinentCd.NORTH_AMERICA.continentCd, "ANTARCTICA", "남극"),
    BAHAMAS(ContinentCd.NORTH_AMERICA.continentCd, "BAHAMAS", "바하마"),
    BELIZE(ContinentCd.NORTH_AMERICA.continentCd, "BELIZE", "벨리즈"),
    BARBADOS(ContinentCd.NORTH_AMERICA.continentCd, "BARBADOS", "바베이도스"),
    BERMUDA(ContinentCd.NORTH_AMERICA.continentCd, "BERMUDA", "버뮤다"),
    BOLIVIA(ContinentCd.NORTH_AMERICA.continentCd, "BOLIVIA", "볼리비아"),
    BRAZIL(ContinentCd.NORTH_AMERICA.continentCd, "BRAZIL", "브라질"),
    IRAQ(ContinentCd.NORTH_AMERICA.continentCd, "IRAQ", "이라크"),
    QATAR(ContinentCd.NORTH_AMERICA.continentCd, "QATAR", "카타르"),

    ARGENTINA(ContinentCd.SOUTH_AMERICA.continentCd, "ARGENTINA", "아르헨티나"),
    CHILE(ContinentCd.SOUTH_AMERICA.continentCd, "CHILE", "칠레"),
    COLOMBIA(ContinentCd.SOUTH_AMERICA.continentCd, "COLOMBIA", "콜롬비아"),
    ECUADOR(ContinentCd.SOUTH_AMERICA.continentCd, "ECUADOR", "에콰도르"),
    PARAGUAY(ContinentCd.SOUTH_AMERICA.continentCd, "PARAGUAY", "파라과이"),
    PERU(ContinentCd.SOUTH_AMERICA.continentCd, "PERU", "페루"),
    SURINAME(ContinentCd.SOUTH_AMERICA.continentCd, "SURINAME", "수리남"),
    URUGUAY(ContinentCd.SOUTH_AMERICA.continentCd, "URUGUAY", "우루과이"),
    VENEZUELA(ContinentCd.SOUTH_AMERICA.continentCd, "VENEZUELA", "베네수엘라")

}